### ISSUE TITLE
allways halt on dtb issue

### ISSUE THREAD

**Issue by kimocoder** [nathanchance/op6-als#1]
how may I properly build the kernel & modules?
Tried most toolchains out there

**Comment by nathanchance** [comment]
`make <env_vars> sdm845-perf_defconfig Image.gz-dtb`

**Comment by kimocoder** [comment]
Yeah.... using linero toolchain...




 CC      security/selinux/ss/services.o
  CC      fs/ext4/page-io.o
../fs/ext4/page-io.c: In function ‘ext4_bio_write_page’:
../fs/ext4/page-io.c:473:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
error, forbidden warning: page-io.c:473
  CC      security/selinux/ss/conditional.o
make[3]: *** [../scripts/Makefile.build:339: fs/ext4/page-io.o] Error 1
make[2]: *** [../scripts/Makefile.build:653: fs/ext4] Error 2
make[1]: *** [/root/Downloads/op6/Makefile:1090: fs] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by nathanchance** [comment]
This source is only guaranteed to build with the stock toolchain, which is GCC 4.9.4. As soon as you use a different toolchain, you will probably have to fix warnings and you are on your own.

**Comment by kimocoder** [comment]
Yeah, after a week with lots of toolchains and some additions to defconfig it worked. Thanks
