### ISSUE TITLE
Can´t compile it

### ISSUE THREAD

**Issue by YAG-Dev** [nathanchance/op6-als#2]
Ubuntu 19.10, Android 10

drivers/Kconfig:215: can't open file "drivers/oneplus/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:112: sdm845_defconfig] Error 1
make: *** [Makefile:589: sdm845_defconfig] Error 2

**Comment by nathanchance** [comment]
You need to either need to clone [this repo](https://github.com/OnePlusOSS/android_vendor_oneplus_opensource_kernel)'s `oneplus/SDM845_Q_10.0` branch into `drivers/oneplus` or make it a submodule. I cannot do this because this repo is meant to be merged into existing kernels.
