### ISSUE TITLE
touchscreen op6t

### ISSUE THREAD

**Issue by ironleopard372** [nathanchance/op6-als#3]
sdm845_p_9.0
hey this compiles perfectly as is.amazing work.it boots perfectly on my 6t..i cannot get the touchscreen to work after fashing in the os or twrp .im new at this but im wondering if the touchscreen drivers might not build..im not sure but any help would b appreciated

**Comment by nathanchance** [comment]
These repos are not really designed to be used standalone, they are designed to be merged into an existent, working source.

Nevertheless, I am not actively working on these repos anymore so closing this up.
